name: 'attestation'
description: 'image attestation'
inputs:
  ATTESTOR:
    required: true
  version:
    required: true
  IMAGE_NAME:
    required: true
  IMAGE_TAG:
    required: true
  GOOGLE_PROJECT_ID:
    required: true
  KMS_KEY:
    required: true
  KMS_KEY_VERSION:
    required: true
  KMS_KEYRING:
    required: true
  KMS_LOCATION:
    required: true
runs:
    using: "composite"
    steps:
      - id: attestation
        shell: bash
        run: |
          # Default parent properties
          ATTESTOR_PROJECT="${ATTESTOR_PROJECT:-${PROJECT_ID}}"
          KMS_PROJECT="${KMS_PROJECT:-${PROJECT_ID}}"



          PUBLIC_KEY_ID=$(gcloud container binauthz attestors describe \
          ${ATTESTOR} --format='value(userOwnedGrafeasNote.publicKeys[0].id)' \
          --project ${GOOGLE_PROJECT_ID})

          IMAGE_DIGEST=$(gcloud container images describe \
          ${IMAGE_NAME}:${IMAGE_TAG} --format='value(image_summary.digest)' \
          --project ${PROJECT_ID})

          # Verify that the image wasn't already attested.
          if gcloud container binauthz attestations list \
                --artifact-url "${IMAGE_NAME}@${IMAGE_DIGEST}" \
                --attestor "${ATTESTOR}" \
                --attestor-project "${GOOGLE_PROJECT_ID}" \
                --format json \
                | jq '.[0].kind' \
                | grep 'ATTESTATION'
          then
            echo "Image has already been attested."
            exit 1
          fi

          gcloud beta container binauthz attestations sign-and-create \
            --project "${GOOGLE_PROJECT_ID}" \
            --artifact-url "${IMAGE_NAME}@${IMAGE_DIGEST}" \
            --attestor "${ATTESTOR}" \
            --attestor-project "${GOOGLE_PROJECT_ID}" \
            --keyversion "${KEY_VERSION}" \
            --keyversion-key "${KMS_KEY}" \
            --keyversion-location "${KMS_LOCATION}" \
            --keyversion-keyring "${KMS_KEYRING}" \
            --keyversion-project "${GOOGLE_PROJECT_ID}"

          # Verify that the image wasn't already attested.
          if gcloud container binauthz attestations list \
                --artifact-url "${IMAGE_NAME}@${IMAGE_DIGEST}" \
                --attestor "${ATTESTOR}" \
                --attestor-project "${GOOGLE_PROJECT_ID}" \
                --format json \
                | jq '.[0].kind' \
                | grep 'ATTESTATION'
          then
            echo "Image has been successfully attested."
            exit 0
          fi

          gcloud --quiet container images add-tag ${IMAGE_NAME}:${IMAGE_TAG} ${IMAGE_NAME}:${IMAGE_TAG}-signed

