name: 'attestation'
description: 'image attestation'
inputs:
  ATTESTOR:
    required: true
  version:
    required: true
  IMAGE_NAME:
    required: true
  IMAGE_TAG:
    required: true
  GOOGLE_PROJECT_ID:
    required: true
  KMS_KEY:
    required: true
  KMS_KEY_VERSION:
    required: true
  KMS_KEYRING:
    required: true
  KMS_LOCATION:
    required: true
runs:
    using: "composite"
    steps:
      - id: attestation
        shell: bash
        run: |
          # Default parent properties
          ATTESTOR_PROJECT="${ATTESTOR_PROJECT:-${PROJECT_ID}}"
          KMS_PROJECT="${KMS_PROJECT:-${PROJECT_ID}}"



          PUBLIC_KEY_ID=$(gcloud container binauthz attestors describe \
          ${{ inputs.ATTESTOR }} --format='value(userOwnedGrafeasNote.publicKeys[0].id)' \
          --project ${{ inputs.GOOGLE_PROJECT_ID }})

          IMAGE_DIGEST=$(gcloud container images describe \
          ${{ inputs.IMAGE_NAME }}:${{ inputs.IMAGE_TAG }} --format='value(image_summary.digest)' \
          --project ${{ inputs.GOOGLE_PROJECT_ID }})

          # Verify that the image wasn't already attested.
          if gcloud container binauthz attestations list \
                --artifact-url "${{ inputs.IMAGE_NAME }}@${IMAGE_DIGEST}" \
                --attestor "${{ inputs.ATTESTOR }}" \
                --attestor-project "${{ inputs.GOOGLE_PROJECT_ID }}" \
                --format json \
                | jq '.[0].kind' \
                | grep 'ATTESTATION'
          then
            echo "Image has already been attested."
            exit 1
          fi

          gcloud beta container binauthz attestations sign-and-create \
            --project "${{ inputs.GOOGLE_PROJECT_ID }}" \
            --artifact-url "${{ inputs.IMAGE_NAME }}@${IMAGE_DIGEST}" \
            --attestor "${{ inputs.ATTESTOR }}" \
            --attestor-project "${{ inputs.GOOGLE_PROJECT_ID }}" \
            --keyversion "${{ inputs.KMS_KEY_VERSION }}" \
            --keyversion-key "${{ inputs.KMS_KEY }}" \
            --keyversion-location "${{ inputs.KMS_LOCATION }}" \
            --keyversion-keyring "${{ inputs.KMS_KEYRING }}" \
            --keyversion-project "${{ inputs.GOOGLE_PROJECT_ID }}"

          # Verify that the image wasn't already attested.
          if gcloud container binauthz attestations list \
                --artifact-url "${{ inputs.IMAGE_NAME }}@${IMAGE_DIGEST}" \
                --attestor "${{ inputs.ATTESTOR }}" \
                --attestor-project "${{ inputs.GOOGLE_PROJECT_ID }}" \
                --format json \
                | jq '.[0].kind' \
                | grep 'ATTESTATION'
          then
            echo "Image has been successfully attested."
            exit 0
          fi

          gcloud --quiet container images add-tag ${{ inputs.IMAGE_NAME }}:${{ inputs.IMAGE_TAG }} ${{ inputs.IMAGE_NAME }}:${{ inputs.IMAGE_TAG }}-signed




