name: Build
on:
  push:
    branches:
      - main
      - qa
jobs:
  build_feature_branch:
    uses: TheKeySupportServices/github-actions/.github/workflows/feature.yml@main
    with:
      GOOGLE_PROJECT_ID: "thekey-dev"
      REGISTRY_URL: "eu.gcr.io"
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      GCR_JSON_KEY: ${{ secrets.GCR_JSON_KEY }}
      BINARY_AUTH_JSON_KEY: ${{ secrets.BINARY_AUTH_JSON_KEY }}

      # The callable workflow behind this can be located via the url provided in the 'uses' definition.
