name: 'whitelist'
description: 'whitelist'
inputs:
  REMOVE_IP:
    default: false
outputs:
  GITHUB_RUNNER_IP:
    value: ${{ steps.whitelist.outputs.GITHUB_RUNNER_IP }}
runs:
    using: "composite"
    steps:
      - id: whitelist
        shell: bash
        run: |
          ARRAY=$(gcloud container clusters list --format="json(name, zone)" | jq -c -r '.[]')
            for item in ${ARRAY[@]}; do
               name=$(echo $item | jq -r '.name')
               zone=$(echo $item | jq -r '.zone')

            REMOVE_IP=${{ inputs.REMOVE_IP }}
            # Get current list of authorized IP addresses.
            IP_LIST=$(gcloud container clusters describe $name --zone=$zone --format="json(masterAuthorizedNetworksConfig.cidrBlocks)" | jq --compact-output --raw-output '.[] | [.cidrBlocks[].cidrBlock]' | sed 's/[]["]//g')

            # Get IP currently being used by this GH runner.
            GH_IP=$(wget -qO- https://ipecho.net/plain ; echo)
            echo "Current Github runner IP: $GH_IP"

            echo ::set-output name=GITHUB_RUNNER_IP::${GH_IP}/32


            # If REMOVE_IP is false then continue to add GH runner ip to authorized ip list.
            if ! $REMOVE_IP; then

              # Append current GH runner ip to current list of authorized IPs
              IP_LIST+=,$GH_IP/32
              # Update cluster with new list of IP addresses including the GH runner IP.
              gcloud container clusters update $name --zone=$zone --enable-master-authorized-networks --master-authorized-networks $IP_LIST
              echo "IP: $GH_IP/32 successfully ADDED to authorized IP list."
            fi


            # If REMOVE_IP input is true then update authorized ip list with current GH runner ip removed.
            if $REMOVE_IP; then
              IP_LIST=$(echo "$IP_LIST" | sed -e "s#,$GH_IP/32##")
              echo $IP_LIST
              gcloud container clusters update $name --zone=$zone --enable-master-authorized-networks --master-authorized-networks $IP_LIST
              echo "IP: $GH_IP/32 successfully REMOVED to authorized IP list."
            fi

          done

