name: 'build-lint-test'
description: 'build'
inputs:
  registry_url:
    required: true
  google_project_id:
    required: true
  tag1:
    required: true
  tag2:
    required: true
  tag3:
    required: true
runs:
    using: "composite"
    steps:
      - name: Build the tagged Docker image
        run: docker build . --file Dockerfile --tag ${{ inputs.registry_url }}/${{ inputs.google_project_id }}/${{ github.event.repository.name }}:${{ inputs.tag1 }} --tag ${{ inputs.registry_url }}/${{ inputs.google_project_id }}/${{ github.event.repository.name }}:${{ inputs.tag2 }} --tag ${{ inputs.registry_url }}/${{ inputs.google_project_id }}/${{ github.event.repository.name }}:${{ inputs.tag3 }}

      - name: Linting
        run: docker run -v /tmp/mount:/app/reports ${{ inputs.registry_url }}/${{ inputs.google_project_id }}/${{ github.event.repository.name }}:${{ inputs.tag1 }} /bin/bash -c "DJANGO_SETTINGS_MODULE=keystone.settings.settings_ci make lint && DJANGO_SETTINGS_MODULE=keystone.settings.settings_ci make django.missing-migrations"

      - name: Generate coverage report
        run: docker run -v /tmp/mount:/app/reports ${{ inputs.registry_url }}/${{ inputs.google_project_id }}/${{ github.event.repository.name }}:${{ inputs.tag1 }} /bin/bash -c "python manage.py jenkins --enable-coverage --settings=keystone.settings.settings_ci"

      - uses: 5monkeys/cobertura-action@master
        with:
          path: /tmp/mount/coverage.xml # Correct path so corb action can review report
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          minimum_coverage: 75
