name: 'build-lint-test'
description: 'build'
inputs:
  registry_url:
    required: true
  google_project_id:
    required: true
  django_settings_module:
    required: true
  linting_enabled:
    required: true
    default: true
  tests_enabled:
    required: true
    default: true
  tag1:
    required: true
  tag2:
    required: true
  tag3:
    required: true
  github_token:
    required: false
  image_name:
    required: true
runs:
    using: "composite"
    steps:
      - name: Build the Docker image
        shell: bash
        run: mkdir -p /tmp/mount/

      - name: Linting
        if: ${{ inputs.linting_enabled == 'true' }}
        shell: bash
        run: docker run -v /tmp/mount/:/app/output/ ${{ inputs.registry_url }}/${{ inputs.google_project_id }}/${{ inputs.image_name }}:${{ inputs.tag1 }} /bin/bash -c "DJANGO_SETTINGS_MODULE=${{ inputs.DJANGO_SETTINGS_MODULE }} make lint && DJANGO_SETTINGS_MODULE=${{ inputs.DJANGO_SETTINGS_MODULE }} make django.missing-migrations"

      - name: Generate coverage report
        if: ${{ inputs.tests_enabled == 'true' }}
        shell: bash
        run: docker run --network host -v /tmp/mount/:/app/output/ ${{ inputs.registry_url }}/${{ inputs.google_project_id }}/${{ inputs.image_name }}:${{ inputs.tag1 }} /bin/bash -c "python manage.py jenkins --enable-coverage --coverage-format=xml --settings=${{ inputs.DJANGO_SETTINGS_MODULE }} && cp -r /app/reports /app/output"

      - uses: 5monkeys/cobertura-action@master
        if: ${{ inputs.tests_enabled == 'true' }}
        with:
          path: /tmp/mount/reports/coverage.xml # Correct path so corb action can review report
          repo_token: ${{ inputs.github_token }}
          only_changed_files: true
          minimum_coverage: 75
        continue-on-error: true
