name: 'build-lint-test'
description: 'build'
inputs:
  registry_url:
    required: true
  google_project_id:
    required: true
  django_settings_module:
    required: true
  linting_enabled:
    required: true
    default: true
  tests_enabled:
    required: true
    default: true
  tag1:
    required: true
  tag2:
    required: true
  tag3:
    required: true
  github_token:
    required: true
runs:
    using: "composite"
    steps:
      - name: Build the tagged Docker image
        shell: bash
        run: docker build . --file Dockerfile --tag ${{ inputs.registry_url }}/${{ inputs.google_project_id }}/${GITHUB_REF##*/}:${{ inputs.tag1 }} --tag ${{ inputs.registry_url }}/${{ inputs.google_project_id }}/${GITHUB_REF##*/}:${{ inputs.tag2 }} --tag ${{ inputs.registry_url }}/${{ inputs.google_project_id }}/${GITHUB_REF##*/}:${{ inputs.tag3 }}

      - name: Linting
        if: ${{ inputs.linting_enabled == 'true' }}
        shell: bash
        run: docker run -v /tmp/mount:/app/reports ${{ inputs.registry_url }}/${{ inputs.google_project_id }}/${GITHUB_REF##*/}:${{ inputs.tag1 }} /bin/bash -c "DJANGO_SETTINGS_MODULE=${{ inputs.DJANGO_SETTINGS_MODULE }} make lint && DJANGO_SETTINGS_MODULE=${{ inputs.DJANGO_SETTINGS_MODULE }} make django.missing-migrations"

      - name: Generate coverage report
        if: ${{ inputs.tests_enabled == 'true' }}
        shell: bash
        run: docker run -v /tmp/mount:/app/reports ${{ inputs.registry_url }}/${{ inputs.google_project_id }}/${GITHUB_REF##*/}:${{ inputs.tag1 }} /bin/bash -c "python manage.py jenkins --enable-coverage --settings=keystone.settings.settings_ci"

      - uses: 5monkeys/cobertura-action@master
        if: ${{ inputs.tests_enabled == 'true' }}
        with:
          path: /tmp/mount/coverage.xml # Correct path so corb action can review report
          repo_token: ${{ inputs.github_token }}
          minimum_coverage: 75
