name: 'import'
description: 'import'
inputs:
  REMOVE_IP:
    default: false
runs:
    using: "composite"
    steps:
      - id: import
        shell: bash
        run: |
          chmod u+x ./env/import.sh && ./env/import.sh

