name: 'tags'
description: 'tags'
outputs:
  env:
    value: ${{ steps.vars.outputs.env }}
  google_project_id:
    value: $(( steps.vars.outputs.google_project_id }}
  branch:
    value: ${{ steps.vars.outputs.branch }}
  commit:
    value: ${{ steps.vars.outputs.commit }}
  datetime:
    value: ${{ steps.vars.outputs.datetime }}
  registry_url:
    value: ${{ steps.vars.outputs.registry_url }}
runs:
    using: "composite"
    steps:
      - id: tags
        shell: bash
        run: |
          if [[ "${{github.base_ref}}" == "main" || "${{github.ref}}" == "refs/heads/main" ]]; then
            echo "::set-output name=google_project_id::thekey-prod"
            echo "::set-output name=env::PROD"
          fi

          if [[ "${{github.base_ref}}" == "qa" || "${{github.ref}}" == "refs/heads/qa" ]]; then
            echo "::set-output name=google_project_id::thekey-qa"
            echo "::set-output name=env::QA"
          fi
          echo ::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})
          echo ::set-output name=commit::$(echo ${GITHUB_SHA})
          echo ::set-output name=datetime::$(date +'%d%m%Y%H%M')
          echo ::set-output name=registry_url::eu.gcr.io