name: 'tags'
description: 'tags'
inputs:
  image_name_override:
    required: false
  binary_auth_json_key_qa:
    required: true
  binary_auth_json_key_prod:
    required: true
outputs:
  env:
    value: ${{ steps.vars.outputs.env }}
  google_project_id:
    value: ${{ steps.vars.outputs.google_project_id }}
  branch:
    value: ${{ steps.vars.outputs.branch }}
  commit:
    value: ${{ steps.vars.outputs.commit }}
  datetime:
    value: ${{ steps.vars.outputs.datetime }}
  registry_url:
    value: ${{ steps.vars.outputs.registry_url }}
  image_name:
    value: ${{ steps.vars.outputs.image_name }}
  kms_key:
    value: ${{ steps.vars.outputs.kms-key }}
  kms_keyring:
    value: ${{ steps.vars.outputs.kms-keyring }}
  attestor:
    value: ${{ steps.vars.outputs.attestor }}
  binary_auth_json_key:
    value: ${{ steps.vars.outputs.binary_auth_json_key }}
runs:
    using: "composite"
    steps:
      - id: vars
        shell: bash
        run: |
          ENV="qa"
          echo "::set-output name=google_project_id::thekey-dev"
          echo "::set-output name=env::qa"
          echo ::set-output name=image_name::$(echo ${{ github.event.repository.name }})
          echo ::set-output name=binary_auth_json_key::test

          if [[ "${{github.base_ref}}" == "main" || "${{github.ref}}" == "refs/heads/main" ]]; then
            echo "::set-output name=google_project_id::thekey-prod"
            echo ::set-output name=binary_auth_json_key::test
            ENV="prod"
          fi

          GIT_BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}

          if [[ "${{ inputs.image_name_override }}" ]]; then
            echo ::set-output name=image_name::$(echo ${{ inputs.image_name_override }})
          fi

          echo ::set-output name=env::${ENV}
          echo ::set-output name=branch::$(echo ${GIT_BRANCH})
          echo ::set-output name=commit::$(echo ${GITHUB_SHA})
          echo ::set-output name=datetime::$(date +'%Y%m%d%H%M')
          echo ::set-output name=registry_url::eu.gcr.io
          echo ::set-output name=kms-key::crypto-key-${ENV}
          echo ::set-output name=kms-keyring::keyring-${ENV}
          echo ::set-output name=attestor::ba-attestor-${ENV}