name: 'tags'
description: 'tags'
inputs:
  image_name_override:
    required: false
outputs:
  env:
    value: ${{ steps.vars.outputs.env }}
  google_project_id:
    value: ${{ steps.vars.outputs.google_project_id }}
  branch:
    value: ${{ steps.vars.outputs.branch }}
  commit:
    value: ${{ steps.vars.outputs.commit }}
  datetime:
    value: ${{ steps.vars.outputs.datetime }}
  registry_url:
    value: ${{ steps.vars.outputs.registry_url }}
  image_name:
    value: ${{ steps.vars.outputs.image_name }}
runs:
    using: "composite"
    steps:
      - id: vars
        shell: bash
        run: |
          echo "::set-output name=google_project_id::thekey-dev"
          echo "::set-output name=env::qa"
          echo ::set-output name=image_name::$(echo ${{ github.event.repository.name }})

          if [[ "${{github.base_ref}}" == "main" || "${{github.ref}}" == "refs/heads/main" ]]; then
            echo "::set-output name=google_project_id::thekey-prod"
            echo "::set-output name=env::prod"
          fi

          GIT_BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}

          if [[ "${{ inputs.image_name_override }}" ]]; then
            echo ::set-output name=image_name::$(echo ${{ github.event.repository.name }})
          fi

          echo ::set-output name=branch::$(echo ${GIT_BRANCH})
          echo ::set-output name=commit::$(echo ${GITHUB_SHA})
          echo ::set-output name=datetime::$(date +'%Y%m%d%H%M')
          echo ::set-output name=registry_url::eu.gcr.io