name: 'changes'
description: 'git changes'
inputs:
  branch:
    required: true
  commit:
    required: true
  datetime:
    require: true
outputs:
  version:
    value: ${{ steps.changes.outputs.version }}
  git_commit:
    value: ${{ steps.changes.outputs.git_commit }}
  last_changes:
    value: ${{ steps.changes.outputs.last_changes }}
runs:
    using: "composite"
    steps:
      - id: changes
        shell: bash
        #run: .github/scripts/git_changes.sh
        run: |
          touch GIT_CHANGES
          git log HEAD^..HEAD --pretty="%h %an - %s" > GIT_CHANGES
          git show -s --format=%H > GIT_COMMIT

          GIT_COMMIT="$(sed -n '1p' 'GIT_COMMIT')"
          echo $(ls -lah)
          LAST_CHANGES="$(cat 'GIT_CHANGES')"
          VERSION="$(sed -n '1p' 'version.txt')"
          echo $LAST_CHANGES
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "GIT_COMMIT=$GIT_COMMIT" >> $GITHUB_ENV
          echo "LAST_CHANGES=<<EOF$LAST_CHANGES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
