name: 'tags'
description: 'tags'
inputs:
  branch:
    required: true
  commit:
    required: true
  datetime:
    require: true
outputs:
  tag1:
    value: ${{ steps.tags.outputs.tag1 }}
  tag2:
    value: ${{ steps.tags.outputs.tag2 }}
  tag3:
    value: ${{ steps.tags.outputs.tag3 }}
runs:
    using: "composite"
    steps:
      - id: tags
        shell: bash
        run: |
          ENV=${{ inputs.branch }}

          if [[ ${{ inputs.branch }} == 'main' || ${{ inputs.branch }} == 'master' ]]; then
            ENV='prod'
          else
            ENV='qa'
          fi

          echo $ENV

          echo ::set-output name=tag1::$(echo $ENV-${{ inputs.commit }}-${{ inputs.datetime }})
          echo ::set-output name=tag2::$(echo $ENV-${{ inputs.commit }})
          echo ::set-output name=tag3::$(echo $ENV)
