name: 'tags'
description: 'tags'
inputs:
  branch:
    required: true
  commit:
    required: true
  datetime:
    require: true
outputs: {}
runs:
    using: "composite"
    steps:
      - shell: bash
        run: |
          echo ::set-output name=tag1::$(echo ${{ github.event.inputs.branch }}-${{ github.event.inputs.commit }}-${{ github.event.inputs.datetime }})
          echo ::set-output name=tag2::$(echo ${{ github.event.inputs.branch }}-${{ github.event.inputs.commit }})
          echo ::set-output name=tag3::$(echo ${{ github.event.inputs.branch }})
