name: 'tags'
description: 'tags'
inputs:
  branch:
    required: true
  commit:
    required: true
  datetime:
    require: true
outputs:
  tag1:
    value: ${{ steps.tags.outputs.tag1 }}
  tag2:
    value: ${{ steps.tags.outputs.tag2 }}
  tag3:
    value: ${{ steps.tags.outputs.tag3 }}
runs:
    using: "composite"
    steps:
      - id: tags
        shell: bash
        run: |
          echo ::set-output name=tag1::$(echo ${{ inputs.branch }}-${{ inputs.commit }}-${{ inputs.datetime }})
          echo ::set-output name=tag2::$(echo ${{ inputs.branch }}-${{ inputs.commit }})
          echo ::set-output name=tag3::$(echo ${{ inputs.branch }})
