name: 'tags'
description: 'tags'
outputs: {}
runs:
    using: "composite"
    steps:
      shell: bash
      - run: |
          echo ::set-output name=tag1::$(echo ${{steps.vars.outputs.branch}}-${{steps.vars.outputs.commit}}-${{steps.vars.outputs.datetime}})
          echo ::set-output name=tag2::$(echo ${{steps.vars.outputs.branch}}-${{steps.vars.outputs.commit}})
          echo ::set-output name=tag3::$(echo ${{steps.vars.outputs.branch}})