name: 'build-lint-test'
description: 'build'
inputs:
  registry_url:
    required: true
  google_project_id:
    required: true
  linting_enabled:
    required: true
    default: true
  tests_enabled:
    required: true
    default: true
  tag1:
    required: true
  tag2:
    required: true
  tag3:
    required: true
  github_token:
    required: true
runs:
    using: "composite"
    steps:
      - name: Build the test Docker image
        if: ${{ inputs.tests_enabled == 'true' }}
        shell: bash
        run: docker build . --file Dockerfile.test --tag ${{ github.event.repository.name }}-test

      - name: Generate coverage report
        if: ${{ inputs.tests_enabled == 'true' }}
        shell: bash
        run: mkdir /tmp/mount && docker create --name ${{ github.event.repository.name }}-test ${{ github.event.repository.name }}-test && docker container start ${{ github.event.repository.name }}-test && docker cp ${{ github.event.repository.name }}-test:/usr/src/app/coverage /tmp/mount/coverage

      - name: Check cov report
        shell: bash
        run: cd /tmp/mount/coverage && sed -i "s|SF:/usr/src/app|SF:$(pwd)|g" lcov.info && ls -lah .

      - name: Report code coverage
        if: ${{ inputs.tests_enabled == 'true' }}
        uses: zgosalvez/github-actions-report-lcov@v1
        with:
          coverage-files: /tmp/mount/coverage/lcov.*.info
          minimum-coverage: 90
          artifact-name: code-coverage-report
          github-token: ${ inputs.github_token }}

      - uses: 5monkeys/cobertura-action@master
        if: ${{ inputs.tests_enabled == 'true' }}
        with:
          path: /tmp/mount/coverage/lcov-report # Correct path so corb action can review report
          repo_token: ${{ inputs.github_token }}
          minimum_coverage: 75

      - name: Delete test image
        shell: bash
        run: docker rmi ${{ inputs.registry_url }}/${{ inputs.google_project_id }}/${{ github.event.repository.name }}:${{ inputs.tag1 }}-test

      - name: Build the tagged Docker image
        shell: bash
        run: docker build . --file Dockerfile --tag ${{ inputs.registry_url }}/${{ inputs.google_project_id }}/${{ github.event.repository.name }}:${{ inputs.tag1 }} --tag ${{ inputs.registry_url }}/${{ inputs.google_project_id }}/${{ github.event.repository.name }}:${{ inputs.tag2 }} --tag ${{ inputs.registry_url }}/${{ inputs.google_project_id }}/${{ github.event.repository.name }}:${{ inputs.tag3 }}

