name: 'Helm Charts'
on:
  workflow_call:
jobs:
  terraform:
    name: 'Helm Charts'
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.8.1

    - name: Install Unittest plugin
      run: helm plugin install https://github.com/quintush/helm-unittest

    - name: Run tests
      id: tests
      run: helm unittest charts/*
