name: 'Helm Charts'
on:
  workflow_call:
env:
  HELM_VERSION: "v3.7.1"
  K8S_TARGET_VERSION: "v1.22.0"
jobs:
  terraform:
    name: 'Helm Charts'
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.8.1

    - name: Install Unittest plugin
      run: helm plugin install https://github.com/quintush/helm-unittest

    - name: Run tests
      id: tests
      run: helm unittest charts/* --helm3

    - uses: cpanato/kubepug-installer@main

    - name: Run Kubepug with your Helm Charts Repository
      run: |
        find charts -mindepth 1 -maxdepth 1 -type d | xargs -t -n1 -I% /bin/bash -c 'helm template % --api-versions ${K8S_TARGET_VERSION} | kubepug --error-on-deprecated --error-on-deleted --k8s-version ${K8S_TARGET_VERSION} --input-file /dev/stdin'


