name: Callable Feature workflow

on:
  workflow_call:
    inputs:
      LINTING_ENABLED:
        required: false
        type: string
        default: true
      TESTS_ENABLED:
        required: false
        type: string
      IMAGE_NAME_OVERRIDE:
        required: false
        type: string
      SITE:
        required: false
        type: string
    secrets:
      SLACK_WEBHOOK_URL:
        required: true
      GCR_JSON_KEY:
        required: true
      BINARY_AUTH_JSON_KEY:
        required: true
      GH_TOKEN:
        required: true
      READ_ONLY_SSH_KEY:
        required: false
      BINARY_AUTH_JSON_KEY_PROD:
        required: false
jobs:
  Docker:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Setup variables
        id: vars
        uses: TheKeySupportServices/github-actions/.github/actions/setup-variables@main
        with:
          image_name_override: ${{ inputs.image_name_override }}

      - uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GCR_JSON_KEY }}
          project_id: ${{ steps.vars.outputs.google_project_id }}
          export_default_credentials: true

      - name: Configure docker
        run: gcloud auth configure-docker -q

      - name: Setup version env vars
        uses: TheKeySupportServices/github-actions/.github/actions/git-changes@main

      - name: Create tags
        id: tags
        with:
          branch: ${{ steps.vars.outputs.branch }}
          commit: ${{ steps.vars.outputs.commit }}
          datetime: ${{ steps.vars.outputs.datetime }}
        uses: TheKeySupportServices/github-actions/.github/actions/create-tags@main

      - name: Slack notification
        uses: slackapi/slack-github-action@v1.18.0
        with:
          # This data can be any valid JSON from a previous step in the GitHub Action
          payload: |
            {
              "username": "Github Workflows/Actions",
              "color": "warning",
              "text": "Started `${{ github.event.repository.name }}/${{steps.vars.outputs.branch}}#${{ github.run_number }}` <https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}|Open in browser>\n\n_The changes:_\n${{ env.LAST_CHANGES }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Build, lint, test
        with:
          linting_enabled: ${{ inputs.LINTING_ENABLED }}
          tests_enabled: ${{ inputs.TESTS_ENABLED }}
          registry_url: ${{ steps.vars.outputs.registry_url }}
          google_project_id: ${{ steps.vars.outputs.google_project_id }}
          environment: ${{ steps.vars.outputs.env }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag1: ${{ steps.tags.outputs.tag1 }}
          tag2: ${{ steps.tags.outputs.tag2 }}
          tag3: ${{ steps.tags.outputs.tag3 }}
          image_name: ${{ steps.vars.outputs.image_name }}
          site: ${{ inputs.SITE }}
        uses: TheKeySupportServices/github-actions/.github/actions/vue-build-lint-test@main

      - name: Slack notification
        uses: slackapi/slack-github-action@v1.18.0
        with:
          # This data can be any valid JSON from a previous step in the GitHub Action
          payload: |
            {
              "username": "Github Workflows/Actions",
              "color": "warning",
              "text": "Build successful/Tests PASSED: `${{ github.event.repository.name }}/${{steps.vars.outputs.branch}}#${{ github.run_number }}` <https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}|Open in browser>"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}